# Map statistic types to required raw data types based on the available database types
STATISTICS_TO_DATA_TYPES = {
    'annual_temperature': ['avg_temperature'],
    'global_temperature': ['glob_temp'],
    'northern_hemisphere_temperature': ['nhem_temp'],
    '64n90n_temperature': ['64n-90n_temp'],
    'annual_spring_temperature': ['avg_temperature'],
    'annual_summer_temperature': ['avg_temperature'],
    'annual_autumn_temperature': ['avg_temperature'],
    'annual_winter_temperature': ['avg_temperature'],
    'annual_winter_temperature': ['avg_temperature'],
    'annual_jan_temperature': ['avg_temperature'],
    'annual_feb_temperature': ['avg_temperature'],
    'annual_mar_temperature': ['avg_temperature'],
    'annual_apr_temperature': ['avg_temperature'],
    'annual_may_temperature': ['avg_temperature'],
    'annual_jun_temperature': ['avg_temperature'],
    'annual_jul_temperature': ['avg_temperature'],
    'annual_aug_temperature': ['avg_temperature'],
    'annual_sep_temperature': ['avg_temperature'],
    'annual_oct_temperature': ['avg_temperature'],
    'annual_nov_temperature': ['avg_temperature'],
    'annual_dec_temperature': ['avg_temperature'],
    'first_frost_autumn': ['avg_temperature'],
    'last_frost_spring': ['avg_temperature'],
    'growing_season_days': ['min_temperature', 'avg_temperature'],
    'growing_season_weeks': ['min_temperature', 'avg_temperature'],
    'coldest_day': ['min_temperature'],
    'warmest_day': ['max_temperature'],
    'coldest_month': ['avg_temperature'],
    'warmest_month': ['avg_temperature'],
    'coldest_week': ['avg_temperature'],
    'warmest_week': ['avg_temperature'],
    'annual_precipitation': ['avg_temperature', 'precipitation'],
    'annual_spring_precipitation': ['avg_temperature','precipitation'],
    'annual_summer_precipitation': ['avg_temperature','precipitation'],
    'annual_autumn_precipitation': ['avg_temperature','precipitation'],
    'annual_winter_precipitation': ['avg_temperature','precipitation'],
    'annual_jan_precipitation': ['avg_temperature','precipitation'],
    'annual_feb_precipitation': ['avg_temperature','precipitation'],
    'annual_mar_precipitation': ['avg_temperature','precipitation'],
    'annual_apr_precipitation': ['avg_temperature','precipitation'],
    'annual_may_precipitation': ['avg_temperature','precipitation'],
    'annual_jun_precipitation': ['avg_temperature','precipitation'],
    'annual_jul_precipitation': ['avg_temperature','precipitation'],
    'annual_aug_precipitation': ['avg_temperature','precipitation'],
    'annual_sep_precipitation': ['avg_temperature','precipitation'],
    'annual_oct_precipitation': ['avg_temperature','precipitation'],
    'annual_nov_precipitation': ['avg_temperature','precipitation'],
    'annual_dec_precipitation': ['avg_temperature','precipitation'],
    'annual_freezeup': ['freezeup'],
    'annual_breakup': ['breakup'],
    'annual_ice_time': ['icetime'],
    'annual_ice_thickness': ['complete_ice_cover'],
    'weekly_co2': ['co2_weekly'],
    'annual_snowdepth_meter': ['snowdepth_meter'],
    'annual_snowdepth_single': ['snowdepth_single'],
    'period_snowdepth': ['snowdepth_single'],
    'glob_temp': ['glob_temp'],
    'nhem_temp': ['nhem_temp'],
    'perma': ['perma'],
}
DATA_TYPES_TO_TYPE = {
    'avg_temperature': 'numeric',
    'glob_temp': 'numeric',
    'nhem_temp': 'numeric',
    '64n-90n_temp': 'numeric',
    'avg_temperature': 'numeric',
    'precipitation': 'numeric',
    'freezeup': 'date',
    'breakup': 'date',
    'icetime': 'numeric',
    'snowdepth_single': 'numeric',
    'snowdepth_meter': 'numeric',
}

# List of all available statistics
ALL_STATISTICS_ = list(STATISTICS_TO_DATA_TYPES.keys())
# filter out nhem_temp, 64n-90n_temp, glob_temp, co2_weekly
ALL_STATISTICS = [stat for stat in ALL_STATISTICS_ if stat not in ['nhem_temp', '64n-90n_temp', 'glob_temp', 'co2_weekly']]

# get all data types from STATISTICS_TO_DATA_TYPES
ALL_DATA_TYPES = list(set([item for sublist in STATISTICS_TO_DATA_TYPES.values() for item in sublist]))
