# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit test 

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master, beta ]
jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
          # windows-latest, macos-latest
              ubuntu-latest]
        node-version: [
                # 10.x, 12.x, 
                # 16.x,
                18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Install semantic-release extra plugins
      run: npm install --save-dev @semantic-release/changelog @semantic-release/git
    - run: npm run build --if-present
    - run: npm test
    - run: git fetch --tags --force
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
